### ISSUE TITLE
I -THINK- npm needs to be upgraded to v7 (Not mandatory - Please advise)

### ISSUE THREAD

**Issue by hossamabdelmoaty** [IBM-SkillsAcademy/BlockchainDeveloper#4]
When i ran npm install using npm v6, i received this warning so i think we better have npm v7 

![image](https://user-images.githubusercontent.com/49478584/133167189-55100a48-7f0b-4c94-afb1-b1c9160ea310.png)

but i noticed that the npm version used with the **Latest LTS Version: of nodejs "14.17.6" (includes npm 6.14.15)** as per the official nodejs website 

![image](https://user-images.githubusercontent.com/49478584/133170025-e0d70d60-ccbc-443f-94df-e9e8109df127.png)

**Comment by labibfarag** [comment]
we will stick to the supported version by node js , no one can grantee that npm V7 will work with node 14.17.x with all cases
