### ISSUE TITLE
Nodejs should be upgraded on VMs to the Latest LTS Version: 14.17.6 (includes npm 6.14.15)

### ISSUE THREAD

**Issue by hossamabdelmoaty** [IBM-SkillsAcademy/BlockchainDeveloper#5]
As per the official website of nodejs, the **Latest LTS Version of nodejs is 14.17.6 (includes npm 6.14.15)**

![image](https://user-images.githubusercontent.com/49478584/133170282-846553cc-abe5-4c8b-bf37-c06e91ca31dd.png)

**Comment by labibfarag** [comment]
at the time of VM installation , this version was not released , so we will stick to the installed version 14.17.5 on the VM, we can't continue upgrading all components every day with newer version and retest all exercises for each minor release.
![image](https://user-images.githubusercontent.com/7271760/133197191-874b0967-054b-4db7-b7b3-4ee79bb53da9.png)
